name: API Call with HMAC-SHA1 Hash
on: [push]

jobs:
  callAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HMAC-SHA1 Hash
        id: generate_hash
        run: |
          timestamp=$(date +%s)
          api_key="${{ secrets.FREEDCAMP_API_KEY }}"
          api_secret="${{ secrets.FREEDCAMP_API_SECRET }}"
          hash=$(echo -n "$api_key$timestamp" | openssl dgst -sha1 -hmac "$api_secret" | awk '{print $2}')
          echo "::set-output name=hash::$hash"
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV
          echo "HASH=$hash" >> $GITHUB_ENV

      - name: Call API with Hash
        run: |
          api_key="${{ secrets.FREEDCAMP_API_KEY }}"
          timestamp=$TIMESTAMP
          hash=$HASH
          curl -X GET "https://freedcamp.com/api/v1/sessions/current?api_key=$api_key&timestamp=$timestamp&hash=$hash"
