name: API Call with HMAC-SHA1 Hash
on: [push]

jobs:
  callAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HMAC-SHA1 Hash
        id: generate_hash
        run: |
          timestamp=$(date +%s)
          api_key="${{ secrets.FREEDCAMP_API_KEY }}"
          api_secret="${{ secrets.FREEDCAMP_API_SECRET }}"
          hash=$(echo -n "$api_key$timestamp" | openssl dgst -sha1 -hmac "$api_secret" | awk '{print $2}')
          echo "::set-output name=hash::$hash"
          touch .env
          echo FREEDCAMP_API_KEY="${{ secrets.FREEDCAMP_API_KEY }}" >> .env
          echo FREEDCAMP_API_SECRET="${{ secrets.FREEDCAMP_API_SECRET }}" >> .env
          echo "TIMESTAMP=$timestamp" >> .env
          echo "HASH=$hash" >> .env

      - name: Call API with Hash
        run: |
          api_key="${{ secrets.FREEDCAMP_API_KEY }}"
          timestamp=$TIMESTAMP
          hash=$HASH
          created_by_id="${{ secrets.FREEDCAMP_CREATED_BY_ID }}"
            curl -X GET 'https://freedcamp.com/api/v1/tasks?api_key=$api_key&timestamp=$timestamp&hash=$hash&limit=200&offset=0&filter%5Bcreated_by_id%5D%5B0%5D=$created_by_id&created_date%5B0%5D=7&sort%5Bpriority%5D=asc'
