name: API Call with HMAC-SHA1 Hash
on: [push]

jobs:
  callAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call API
        run: |
          const fetch = require('node-fetch');

          const endpoint = process.env.FREEDCAMP_API_ENDPOINT;
          const apiKey = process.env.FREEDCAMP_API_KEY;
          const apiSecret = process.env.FREEDCAMP_API_SECRET;
          const timestamp = Math.floor(Date.now() / 1000);
          const hash = require('crypto').createHmac('sha1', apiSecret).update(apiKey + timestamp).digest('hex');
          const createdByID = process.env.FREEDCAMP_CREATED_BY_ID;

          fetch(`${endpoint}?api_key=${apiKey}&timestamp=${timestamp}&hash=${hash}&limit=200&offset=0&filter%5Bcreated_by_id%5D%5B%5D=${createdByID}&filter%5Bcreated_date%5D%5B%5D=7&order%5Bpriority%5D=asc`)
            .then(response => response.json())
            .then(data => {
              data.tasks.forEach(task => {
                const taskId = task.id;
                const newTitle = `#${taskId} - ${task.title.replace(/^#/, '')}`;
                if (!newTitle.startsWith('#')) {
                  console.log(`Updating task with ID ${taskId} to new title: ${newTitle}`);
                  fetch(`${endpoint}${taskId}?api_key=${apiKey}&timestamp=${timestamp}&hash=${hash}`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'multipart/form-data' },
                    body: JSON.stringify({ title: newTitle })
                  });
                }
              });
            })
            .catch(error => console.error(error));
