name: Freedcamp Bot
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - "main"
jobs:
  make-bot:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: "Create env file"
        run: |
          echo FREEDCAMP_API_KEY="${{ secrets.FREEDCAMP_API_KEY }}" >> .env
          echo FREEDCAMP_API_SECRET="${{ secrets.FREEDCAMP_API_SECRET }}" >> .env
          echo FREEDCAMP_CREATED_BY_ID="${{ secrets.FREEDCAMP_CREATED_BY_ID }}" >> .env

      - name: Run handle freedcamp
        run: php artisan handle:freedcamp
